#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/sxhkd/sxhkdrc.bspwm &
pgrep -x polybar > /dev/null || polybar &
pgrep -x picom > /dev/null || picom &
pgrep -x dunst > /dev/null || dunst &
feh --bg-fill -z ~/.config/wallpapers/*
# nitrogen --restore &
pgrep -x nm-applet > /dev/null || nm-applet &

bspc monitor -d 1 2 3 4 5 6 7 8 9 


bspc config border_width 1
bspc config window_gap 12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^1' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a TelegramDesktop desktop='^6' follow=on
bspc rule -a Nitrogen follow=on state=floating
bspc rule -a kitty follow=on desktop='^2'
